### PR TITLE
Enable graphite

### PR DESCRIPTION
**Pull request by renatoathaydes**
This PR changes the master branch from BushnevYuri to enable the graphite protocol in InfluxDB.
It makes the graphite port, 2003, open to the host machine so that it can push data into it.

This is being used by our load tests written with Gatling.

### CODE REVIEW

**Comment by fredrikbackstrom** [comment]
The graphite format is something we want to move away from and use the native format of influx as when writing the graphite format is not performant for influx and it does not use tags which is the influx preferred way. This works for the Gatlin PR but my thought is more that you should investigate if gatlin cannot write to influx instead of graphite format.

**Comment by renatoathaydes** [comment]
I couldn't find any other writers for InfluxDB, but Gatling allows us to write our own data-writer if we need to:

https://github.com/gatling/gatling/blob/master/gatling-core/src/main/scala/io/gatling/core/stats/writer/DataWriter.scala

We could try to implement one ourselves that does something nicer.

**Comment by fredrikbackstrom** [comment]
nice, before doing to much we should decide on locust vs. gattling or if both are ok and we won't care.

**Comment by renatoathaydes** [comment]
I want to be able to run these tests in "special" builds later (driven by the test engine which we have been discussing), and for that reason, I think sticking with the JVM makes more sense... But having extra tests in other frameworks is always a good thing because we can compare results...

**Pull request merged**
